-- ============================================================
-- SEED DE DADOS DE TESTE — KroosProject
-- ============================================================
--
-- Este ficheiro foi mantido apenas por compatibilidade histórica.
-- Os INSERTs de dados de teste estão agora consolidados em:
--   basededados/kroosproject.sql
--
-- Para instalar a base de dados completa (estrutura + dados de teste),
-- importa apenas o ficheiro principal:
--   basededados/kroosproject.sql
--
-- Este script não executa inserts para evitar duplicação.
